import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getUsers } from '../utils/users'
import React, { useEffect, useState } from 'react';
import { signInWithGoogle } from "../utils/firebase"
// import firebase from "../utils/firebase";
// import { initializeApp } from "firebase/app";




export default function Home() {
  useEffect(() => {
    getUsers();
  }, []);

  function GoogleLogin(){
    console.log('Login Btn Call')
  
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Stack Smashers
        </h1>


        <div id="LoginScreen" className={styles.grid}>

          <a className={styles.card}>
           <button className={styles.card} onClick = {signInWithGoogle} id="LoginScreen"> <h2> Login with Google</h2></button>
          </a>
    
        </div>
      </main>
    </div>
  )
}
